# Generated by Django 5.2.6 on 2025-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
