# Generated by Django 5.2.6 on 2025-09-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('side', 'Side'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('combo', 'Combo'), ('breakfast', 'Breakfast'), ('kids', 'Kids'), ('salad', 'Salad'), ('soup', 'Soup'), ('pasta', 'Pasta'), ('pizza', 'Pizza'), ('burger', 'Burger'), ('grill', 'Grill'), ('sushi', 'Sushi'), ('noodles', 'Noodles')], default='main', max_length=24),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('african', 'African'), ('american', 'American'), ('asian', 'Asian'), ('bbq', 'BBQ'), ('burger', 'Burger'), ('chinese', 'Chinese'), ('coffee', 'Coffee'), ('dessert', 'Dessert'), ('french', 'French'), ('greek', 'Greek'), ('indian', 'Indian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('lebanese', 'Lebanese'), ('mexican', 'Mexican'), ('pizza', 'Pizza'), ('seafood', 'Seafood'), ('sushi', 'Sushi'), ('thai', 'Thai'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian')], default='asian', max_length=32),
        ),
    ]
