# Generated by Django 5.2.6 on 2025-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main Course'), ('side', 'Side Dish'), ('dessert', 'Dessert'), ('drink', 'Beverage'), ('pizza', 'Pizza'), ('burger', 'Burger'), ('sushi', 'Sushi'), ('pasta', 'Pasta'), ('salad', 'Salad'), ('soup', 'Soup'), ('grill', 'Grilled'), ('noodles', 'Noodles'), ('sandwich', 'Sandwich'), ('wrap', 'Wrap'), ('taco', 'Taco'), ('bowl', 'Bowl'), ('combo', 'Combo Meal'), ('breakfast', 'Breakfast'), ('kids', 'Kids Menu'), ('appetizer', 'Appetizer'), ('snack', 'Snack')], default='main', max_length=24),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('french', 'French'), ('italian', 'Italian'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('indian', 'Indian'), ('thai', 'Thai'), ('mexican', 'Mexican'), ('greek', 'Greek'), ('lebanese', 'Lebanese'), ('american', 'American'), ('african', 'African'), ('mediterranean', 'Mediterranean'), ('asian', 'Asian'), ('middle_eastern', 'Middle Eastern'), ('european', 'European'), ('latin_american', 'Latin American'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('healthy', 'Healthy'), ('fusion', 'Fusion')], default='asian', max_length=32),
        ),
    ]
